language: php
sudo: false
php:
- '5.6'
env:
  global:
  - GIT_COMMITTER_NAME=kassy000
  - GIT_COMMITTER_EMAIL=kashihara_ybb@yahoo.co.jp
  - GIT_AUTHOR_NAME=kassy000
  - GIT_AUTHOR_EMAIL=kashihara_ybb@yahoo.co.jp
  - secure: AlvvRZoPxuEPSIaXQJQUJeqA8dOvf1w7TjHYOupIiaHs9Y5iaTlRYRtsCWiSNZ2RPqzmir9SXAoyMQYWoYH7PBBOE6xv09KnKz1fvMxBEZBJdVHwAntpHADJosWi5Ad5cnim51rcAX/Sjd/NAvqXQLnf6FZRsyytisLWa9tXMTIW9dGQjk053kz+euGeL+zly1QvPZDcVpuatxMot6fVcXY/0JGR6FJp0SC2TNXtvxCQRvZ3E7xklbeiQbC2bqbDIGMiaE8pMpzUwLmD46NGIgGapfUFq23rsh9gWpXPeoV4a9GnkWgmBXt/H9fLOaK5O+tp3hly/mqJ+4yUdmCoP9Q85DT9XDOGT+RfkZ+pkXMxivvzHrotL+AK8iHyWLEKz5wzjJxT64d1oEzvyJQtKVw0/mT3YVYI60evLr/4YwtFBOYoq+ASNmd2EGMH5SdQ/FoSAxpIxpCJK/hSMTHaeSkGUJ0t/qfCufNCXRnNWQ7S2QQYx8/IhEpWAABSVYsI4MDR8w4WdqFAZPmwU7u0GDufDO7+WHLBliqsqfGHmNiDGqA5uP+or0Tf+HDqXVm2DHmW3asT5IVTe/4XGPc3uUWiUv1+pZNrvwKx6MJTBgUwrJ1fxHoCz4ngDYXSUfrWCpMsbqP40eYKoq+Ce6KjGinSw45NNd0mEYu3Mw37Yxc=
before_script:
- nvm install 4.2
- npm install
script:
- find . \( -name '*.php' \) -exec php -lf {} \;
after_success:
- run npm dist
- bash ./bin/deploy.sh
